name: 'Test PAC File'
description: 'Test the supplied PAC file against a result.'
inputs:
  file: # path to file
    description: 'path to file'
    required: true
  url: # url to test
    description: 'the url to test again'
    required: true
outputs:
  result: # the result from the PAC file.
    description: 'The result of this PAC file test'
runs:
  using: 'node16'
  main: 'dist/index.js'
