name: 'Test PAC File'
description: 'Test the supplied PAC file against a result.'
inputs:
  file: # path to file
    description: 'path to file'
    required: true
  url: # url to test
    description: 'the url to test again'
    required: true
  result: #expected result
    description: 'the expected result from the PAC File'
    required: true
outputs:
  result: # the result from the PAC file.
    description: 'The result of this PAC file test'
runs:
  using: 'node20'
  main: 'dist/index.js'
